/*
    Problem Code- DOUBLERENT
    Problem Name- Double Rent
    Problem Link- https://www.codechef.com/practice/course/basic-programming-concepts/DIFF500/problems/DOUBLERENT
    Description- Chefina decided to move into Chef's apartment. Chef was initially paying a rent of X rupees. Since 
    Chefina is moving in, the owner decided to double the rent. Find the final rent Chef needs to pay.
*/

#include <bits/stdc++.h>
using namespace std;

int main(){
    int rent;
    cin >> rent;
    cout << rent*2 << endl;
    return 0;
}