/*
    Problem Code- 1068
    Problem Name- Weird Algorithm
    Problem Link- https://cses.fi/problemset/task/1068
    Description- Given a number n, print the sequence generated by the following algorithm:
                 if n is even, divide it by 2
                 if n is odd, multiply it by 3 and add 1
                 The algorithm ends when n = 1.
*/
#include <iostream>
using namespace std;
int main(){
    long long n;
    cin>>n;
    while(n != 1){
        cout<< n << " ";
        if(n % 2 == 0){
            n = n /2;
        }else{
            n *= 3;
            n += 1;
        }
    }
    cout<< 1 << endl;
    return 0;
}